### ISSUE TITLE
Health check for sync status

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-chart#5]
Can be:
- Sidecar
- Extended container 

Container already has status off 9000 rest port 

Validate that LB responds to this

**Comment by robcxyz** [comment]
https://github.com/Kludex/fastapi-health

Readiness should be tied to some SOT BH metric /readyz -> 200 + (extra if ?verbose=true) 
```
[+]ping ok
[+]log ok
```
Healthiness should be bool /healthz -> same

**Comment by shinyfoil** [comment]
Container is ready to go here: https://github.com/geometry-labs/icon-node-health-sidecar

Produces both a standard `200 OK` and `503 UNHEALTHY` and a verbose output when required.

Will need to add to chart and test.
